### ISSUE TITLE
Setup team canvases automatically by calling URL?

### ISSUE THREAD

**Issue by b-g** [b-g/p5-shared-canvas-websocket#2]
Currently working on a shared canvas for some drawing experiments with students out of Corona Home Office ... see https://p5-shared-canvas-websocket.glitch.me/ (have to browser taps open and start scribbling). It already works!

Now just a breakout team canvas feature is missing. What I want:
- `https://p5-shared-canvas-websocket.glitch.me/` If users calls this url they are all together in a single shared canvas ... this is already working
- `https://p5-shared-canvas-websocket.glitch.me/team/{name}` I'm imagine that some of the people want to break out in smaller groups. Now it would be really cool if one could open up a custom shared canvas simply by typing an URL in the browser e.g. `https://p5-shared-canvas-websocket.glitch.me/team/picasso-gang`

I'm aware of e.g. https://gist.github.com/companje/0a42eb25dd3caff92ab7 ... but I can't figure out how to open a new shared canvas dynamically, as the server seems to have to know the namescape of the new generated shared canvas in advanced. Any idea/pointers how to do that in an easy way?

**Comment by b-g** [comment]
See also the "professional" server implementation by Mr.doob (maker of three.js)

https://twitter.com/mrdoob/status/1250408940795334656
https://glitch.com/edit/#!/multiuser-sketchpad

**Comment by tdurand** [comment]
I made a PR for this..  It might be possible with "namespace" but I also struggled, and it is pretty simple to implement with the "rooms" API of socket.io  : https://github.com/b-g/p5-shared-canvas-websocket/pull/3

**Comment by b-g** [comment]
@tdurand Mega + many thanks!! Merged :)
